# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/great/Unreal Engine/UE_5.4.4
GAMEPROJECTFILE =/home/great/Documents/Unreal Projects/GoapSystemUpgrade/GoapSystemUpgrade.uproject

TARGETS = \
	GoapSystemUpgrade-Linux-DebugGame  \
	GoapSystemUpgrade-Linux-Shipping  \
	GoapSystemUpgrade \
	GoapSystemUpgradeEditor-Linux-DebugGame  \
	GoapSystemUpgradeEditor-Linux-Shipping  \
	GoapSystemUpgradeEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend GoapSystemUpgradeEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug GoapSystemUpgradeEditor-Linux-Debug


GoapSystemUpgrade-Linux-DebugGame:
	 $(PROJECTBUILD) GoapSystemUpgrade Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

GoapSystemUpgrade-Linux-Shipping:
	 $(PROJECTBUILD) GoapSystemUpgrade Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

GoapSystemUpgrade:
	 $(PROJECTBUILD) GoapSystemUpgrade Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

GoapSystemUpgradeEditor-Linux-DebugGame:
	 $(PROJECTBUILD) GoapSystemUpgradeEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

GoapSystemUpgradeEditor-Linux-Shipping:
	 $(PROJECTBUILD) GoapSystemUpgradeEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

GoapSystemUpgradeEditor:
	 $(PROJECTBUILD) GoapSystemUpgradeEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
